In [39]:
#Import library numpy, pandas dan sclikit-learn
import numpy as np
import pandas as pd
from sklearn import tree

In [40]:
#Membaca dataset dari file ke pandas dataFrame
irisDataset = pd.read_csv('klasifikasi_dataset_iris_oke.csv', delimiter=',', header=0)

In [41]:
irisDataset.head()

id  SepalLengthCm  ...  PetalWidthCm          Species
0   1              7  ...            19  Iris-versicolor
1   2              3  ...            19  Iris-versicolor
2   3             10  ...            20  Iris-versicolor
3   4              9  ...            17  Iris-versicolor
4   5              8  ...            15  Iris-versicolor

[5 rows x 6 columns]

In [42]:
#mengubah kelas (kolom "species") dari string ke unique-integer
irisDataset["Species"] = pd.factorize(irisDataset.Species)[0]

In [43]:
irisDataset.head()

id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1              7            12             26            19        0
1   2              3            13             26            19        0
2   3             10            11             24            20        0
3   4              9            12             23            17        0
4   5              8            14             29            15        0

In [44]:
print(irisDataset)

     id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0     1              7            12             26            19        0
1     2              3            13             26            19        0
2     3             10            11             24            20        0
3     4              9            12             23            17        0
4     5              8            14             29            15        0
..  ...            ...           ...            ...           ...      ...
95   96              3            16             17            16        0
96   97              8            17             20            16        0
97   98              2            11             20            20        0
98   99              6            20             16            19        0
99  100              8            18             30            20        0

[100 rows x 6 columns]


In [45]:
#menghapus kolom "id"
irisDataset = irisDataset.drop(labels="id", axis=1)

In [46]:
print(irisDataset)

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0               7            12             26            19        0
1               3            13             26            19        0
2              10            11             24            20        0
3               9            12             23            17        0
4               8            14             29            15        0
..            ...           ...            ...           ...      ...
95              3            16             17            16        0
96              8            17             20            16        0
97              2            11             20            20        0
98              6            20             16            19        0
99              8            18             30            20        0

[100 rows x 5 columns]


In [47]:
#mengubah dataframe ke array numpy
irisDataset = irisDataset.to_numpy()

In [48]:
print(irisDataset)

[[ 7 12 26 19  0]
 [ 3 13 26 19  0]
 [10 11 24 20  0]
 [ 9 12 23 17  0]
 [ 8 14 29 15  0]
 [ 6 17 19 17  0]
 [ 5 10 26 19  0]
 [ 4 20 16 15  0]
 [ 2 18 22 15  0]
 [ 9 12 29 18  0]
 [ 1 10 23 20  0]
 [ 7 15 16 19  0]
 [ 1 19 16 19  0]
 [ 6 14 17 19  0]
 [ 4 20 27 16  0]
 [ 7 12 20 16  0]
 [ 8 15 19 19  0]
 [ 8 13 24 17  0]
 [ 2 15 17 19  0]
 [ 7 14 15 17  0]
 [ 9 10 29 18  0]
 [ 9 20 17 18  0]
 [ 4 11 17 19  0]
 [ 6 14 15 18  0]
 [ 4 12 26 18  0]
 [ 6 17 30 19  0]
 [ 4 10 27 15  0]
 [ 7 10 24 17  0]
 [ 9 19 23 20  0]
 [10 13 30 19  0]
 [ 4 18 16 18  0]
 [10 17 21 15  0]
 [10 13 30 18  0]
 [ 7 10 19 16  0]
 [10 12 24 16  0]
 [ 2 13 19 20  0]
 [ 4 13 21 18  0]
 [ 6 20 20 17  0]
 [ 1 19 17 20  0]
 [ 7 19 23 16  0]
 [ 1 16 21 17  0]
 [ 6 18 18 16  0]
 [ 8 12 25 17  0]
 [ 3 13 29 17  0]
 [ 5 19 16 20  0]
 [ 8 19 22 18  0]
 [ 6 16 18 17  0]
 [ 8 15 29 16  0]
 [ 2 10 22 15  0]
 [10 11 24 20  0]
 [ 9 13 24 19  0]
 [ 8 19 21 15  0]
 [ 4 11 23 15  0]
 [ 9 16 26 16  0]
 [ 3 13 24 16  0]
 [ 8 13 30

In [49]:
#membagi dataset => 80 baris data untuk training dan 20 baris data untuk testing
dataTraining = np.concatenate((irisDataset[0:40, :], irisDataset[50:90, :]), axis=0)
dataTesting = np.concatenate((irisDataset[40:50, :], irisDataset[90:100, :]), axis=0)                              

In [50]:
print(dataTraining)
len(dataTraining)

[[ 7 12 26 19  0]
 [ 3 13 26 19  0]
 [10 11 24 20  0]
 [ 9 12 23 17  0]
 [ 8 14 29 15  0]
 [ 6 17 19 17  0]
 [ 5 10 26 19  0]
 [ 4 20 16 15  0]
 [ 2 18 22 15  0]
 [ 9 12 29 18  0]
 [ 1 10 23 20  0]
 [ 7 15 16 19  0]
 [ 1 19 16 19  0]
 [ 6 14 17 19  0]
 [ 4 20 27 16  0]
 [ 7 12 20 16  0]
 [ 8 15 19 19  0]
 [ 8 13 24 17  0]
 [ 2 15 17 19  0]
 [ 7 14 15 17  0]
 [ 9 10 29 18  0]
 [ 9 20 17 18  0]
 [ 4 11 17 19  0]
 [ 6 14 15 18  0]
 [ 4 12 26 18  0]
 [ 6 17 30 19  0]
 [ 4 10 27 15  0]
 [ 7 10 24 17  0]
 [ 9 19 23 20  0]
 [10 13 30 19  0]
 [ 4 18 16 18  0]
 [10 17 21 15  0]
 [10 13 30 18  0]
 [ 7 10 19 16  0]
 [10 12 24 16  0]
 [ 2 13 19 20  0]
 [ 4 13 21 18  0]
 [ 6 20 20 17  0]
 [ 1 19 17 20  0]
 [ 7 19 23 16  0]
 [ 9 13 24 19  0]
 [ 8 19 21 15  0]
 [ 4 11 23 15  0]
 [ 9 16 26 16  0]
 [ 3 13 24 16  0]
 [ 8 13 30 16  0]
 [ 4 14 16 17  0]
 [ 8 17 21 20  0]
 [ 3 19 19 17  0]
 [ 6 12 29 17  0]
 [ 7 12 26 19  0]
 [ 8 14 26 19  0]
 [ 9 14 29 20  0]
 [ 6 11 21 16  0]
 [ 3 15 20 18  0]
 [ 7 18 30

80

In [51]:
print(dataTesting)
len(dataTesting)

[[ 1 16 21 17  0]
 [ 6 18 18 16  0]
 [ 8 12 25 17  0]
 [ 3 13 29 17  0]
 [ 5 19 16 20  0]
 [ 8 19 22 18  0]
 [ 6 16 18 17  0]
 [ 8 15 29 16  0]
 [ 2 10 22 15  0]
 [10 11 24 20  0]
 [ 7 19 18 15  0]
 [ 9 20 27 20  0]
 [ 5 14 21 15  0]
 [ 2 16 23 19  0]
 [ 1 11 16 17  0]
 [ 3 16 17 16  0]
 [ 8 17 20 16  0]
 [ 2 11 20 20  0]
 [ 6 20 16 19  0]
 [ 8 18 30 20  0]]


20

In [52]:
#memecah dataset ke input label
inputTraining = dataTraining[:, 0:4]
inputTesting = dataTesting[:, 0:4]
labelTraining = dataTraining[:, 4]
labelTesting = dataTesting[:, 4]
print(labelTraining)
len(labelTraining)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0]


80

In [53]:
#mendefinisikan decision tree classifier
model = tree.DecisionTreeClassifier()

In [54]:
#mentraining model
model = model.fit(inputTraining, labelTraining)

In [55]:
#memprediksi input data testing
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi : ", hasilPrediksi)

Label Sebenarnya :  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Hasil Prediksi :  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [56]:
#menghitung akurasi
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar :", prediksiBenar, "data")
print("Prediksi Salah :", prediksiSalah, "data")
print("Akurasi :", prediksiBenar/(prediksiBenar+prediksiSalah) * 100, "%")

Prediksi Benar : 20 data
Prediksi Salah : 0 data
Akurasi : 100.0 %
